### ISSUE TITLE
Making the example html a bit more responsive

### ISSUE THREAD

**Issue by raul1991** [ashish-chopra/angular-gauge#12]
Using the window resize event , the graphs can be updated. 
### Changes to be done
1. Setters for the width and height
2. An event listener 

``` Javascript
window.addEventListener('resize', function() {
  this.context.canvas.width = window.height - someBorderOffset; //someBorderOffset - for the browser's border width.
  this.context.canvas.width = window.width - someBorderOffset; 
  gauge.update();
});
```

**Comment by ashish-chopra** [comment]
Responsive gauge is an enhancement. This will be taken up in future. But you can also contribute if you can. Thanks.

**Comment by raul1991** [comment]
Canvas is already adjusting itself on window resize. What this issue should be now is removing a css property due to which the gui distorts on resize operation. Changing the title now.

**Comment by ashish-chopra** [comment]
Canvas resize is required for accommodating the fluid layouts. Canvas currently not resizing. With your patch, only the example html is resizing as per the window resizing. 

Also with the current fix, the view of example html in desktop layout get distorted. Make sure we maintain the same layout as shown in the screenshot of the example. So in order to fix the example's responsiveness you need to use media queries. And for Gauge's responsiveness you need to implement code to resize canvas.

**Comment by ashish-chopra** [comment]
Example html has been redesigned as a "playground" now. Checkout a snapshot below: 

![playground](https://cloud.githubusercontent.com/assets/1948545/23940724/183f221c-098c-11e7-986c-3d36df65894e.png)

Take the latest pull or update your dependencies to v1.3.0, this playground will be available.
