### ISSUE TITLE
Update function does not work as it should

### ISSUE THREAD

**Issue by raul1991** [ashish-chopra/angular-gauge#26]
Clicking the update button on the gh-pages branch (calls the update function of the gauge) does not really clears the previously drawn arc if you press it frequently and results into an inconsistent gauge.

Have a look at the following picture.
![image](https://cloud.githubusercontent.com/assets/1281636/23689919/c4e142f6-03e3-11e7-8de2-0d0d5d758315.png)

**Comment by ashish-chopra** [comment]
Good, its a know issue, but was taken on low priority as it will not effect any real world app, unless it is realtime udpate. But yes please send a pull request with a fix, i you can.

**Comment by ashish-chopra** [comment]
The bug was a problem with animation's mathematical equation and rendering logic. In the latest release [v1.4.0](https://github.com/ashish-chopra/angular-gauge/releases/tag/v1.4.0), i have re-written the underlying gauge logic, thereby eradicating this issue and many more. Checkout the release note and take an upgrade. 

Thanks!
