### ISSUE TITLE
Is it possible to show more than one value at the same time?

### ISSUE THREAD

**Issue by tmontanaro** [ashish-chopra/angular-gauge#56]
Is it possible to show more than one value at the same time?
To let you understand what I'm thinking, you can see the following image:

![Multiple values in Gauge](https://user-images.githubusercontent.com/6121394/43390099-aae366fe-93ed-11e8-951c-7d0d7449bf5f.png)
(image from http://www.datarevelations.com/wp-content/uploads/2016/06/Stacked-donut.png)

**Comment by ashish-chopra** [comment]
Hi @tmontanaro

 This is not possible with angular-gauge natively. However, with tricks, you can stack multiple angular-gauge together to achieve it but I don't recommend that because it is a hack, not a sustainable solution. 

You can look for other chart types which better match your situation. Maybe gauge is not the right fit for this problem.

Thanks!
